version: 2
updates:
  - package-ecosystem: gomod
    directory: /fisherman
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
