package slurp

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"syscall"

	"github.com/tuna-os/fisherman/internal/progress"
	"github.com/tuna-os/fisherman/internal/runner"
)

// SlurpConfig describes what data to extract from a Windows partition.
// Generated by the GUI from a ScanResult + user selection.
type SlurpConfig struct {
	// SourcePartition is the NTFS partition to read from.
	SourcePartition string `json:"sourcePartition"`
	// Users maps Windows username → list of category names to extract.
	Users []SlurpUserConfig `json:"users"`
}

// SlurpUserConfig describes which categories to extract for one Windows user.
type SlurpUserConfig struct {
	Name       string   `json:"name"`
	Categories []string `json:"categories"` // e.g. ["Documents", "Pictures", "Desktop"]
}

// DataSlurpResult describes the outcome of a full data extraction.
type DataSlurpResult struct {
	Found      bool
	ScratchDir string
	TotalBytes int64
	FileCount  int
	Users      []SlurpUserResult
}

// SlurpUserResult tracks what was extracted for one user.
type SlurpUserResult struct {
	Name       string
	Categories []SlurpCategoryResult
}

// SlurpCategoryResult tracks what was extracted for one category.
type SlurpCategoryResult struct {
	Name  string
	Bytes int64
	Count int
}

// AvailableScratchBytes returns how much RAM-backed scratch space is available
// in /run, leaving a 2GB safety margin for the system.
func AvailableScratchBytes() int64 {
	var st syscall.Statfs_t
	if err := syscall.Statfs("/run", &st); err != nil {
		return 0
	}
	available := int64(st.Bavail) * int64(st.Bsize)
	// Reserve 2GB for system use
	const reserve = 2 * 1024 * 1024 * 1024
	if available <= reserve {
		return 0
	}
	return available - reserve
}

// ExtractData performs the full data slurp: mounts the NTFS partition read-only
// and copies selected user data categories to RAM-backed scratch.
// This must be called BEFORE partitioning. Returns the result for later injection.
func ExtractData(config *SlurpConfig) (*DataSlurpResult, error) {
	if config == nil || config.SourcePartition == "" || len(config.Users) == 0 {
		return nil, fmt.Errorf("no slurp config provided")
	}

	result := &DataSlurpResult{ScratchDir: filepath.Join(scratchBase, "data")}

	if err := os.MkdirAll(result.ScratchDir, 0o755); err != nil {
		return nil, fmt.Errorf("creating data scratch: %w", err)
	}
	if err := os.MkdirAll(ntfsMountPoint, 0o755); err != nil {
		return nil, fmt.Errorf("creating mount point: %w", err)
	}

	// Mount NTFS read-only
	progress.Substep("Mounting Windows partition for data migration")
	if err := runner.Run("mount", "-t", "ntfs3", "-o", "ro,noatime", config.SourcePartition, ntfsMountPoint); err != nil {
		if err2 := runner.Run("mount", "-t", "ntfs-3g", "-o", "ro,noatime", config.SourcePartition, ntfsMountPoint); err2 != nil {
			return nil, fmt.Errorf("mount NTFS: ntfs3: %v, ntfs-3g: %v", err, err2)
		}
	}
	defer func() {
		_ = runner.Run("umount", ntfsMountPoint)
		os.Remove(ntfsMountPoint)
	}()

	budget := AvailableScratchBytes()
	progress.Info(fmt.Sprintf("Data migration scratch budget: %s", humanBytes(budget)))

	usersDir := filepath.Join(ntfsMountPoint, "Users")
	var totalCopied int64

	for _, userCfg := range config.Users {
		profileDir := filepath.Join(usersDir, userCfg.Name)
		if _, err := os.Stat(profileDir); err != nil {
			progress.Info(fmt.Sprintf("Warning: user profile %q not found, skipping", userCfg.Name))
			continue
		}

		userResult := SlurpUserResult{Name: userCfg.Name}
		userScratch := filepath.Join(result.ScratchDir, userCfg.Name)

		for _, catName := range userCfg.Categories {
			catPath := categoryPath(catName)
			if catPath == "" {
				continue
			}

			srcDir := filepath.Join(profileDir, catPath)
			if _, err := os.Stat(srcDir); err != nil {
				continue
			}

			dstDir := filepath.Join(userScratch, catName)
			if err := os.MkdirAll(dstDir, 0o755); err != nil {
				continue
			}

			progress.Substep(fmt.Sprintf("Copying %s/%s", userCfg.Name, catName))

			catResult := SlurpCategoryResult{Name: catName}
			copied, count := streamCategory(srcDir, dstDir, budget-totalCopied)
			catResult.Bytes = copied
			catResult.Count = count
			totalCopied += copied
			result.FileCount += count

			userResult.Categories = append(userResult.Categories, catResult)

			// Check budget
			if totalCopied >= budget {
				progress.Info("Scratch space budget reached — stopping data migration")
				break
			}
		}

		if len(userResult.Categories) > 0 {
			result.Users = append(result.Users, userResult)
		}
		if totalCopied >= budget {
			break
		}
	}

	result.TotalBytes = totalCopied
	result.Found = totalCopied > 0

	if result.Found {
		progress.Info(fmt.Sprintf("Migrated %s (%d files) from Windows", humanBytes(totalCopied), result.FileCount))
	}

	return result, nil
}

// streamCategory copies files from srcDir to dstDir, respecting a byte budget.
// Returns total bytes copied and file count.
func streamCategory(srcDir, dstDir string, budget int64) (int64, int) {
	var totalBytes int64
	var count int

	_ = filepath.Walk(srcDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil //nolint:nilerr // best-effort: absent/unreadable source → skip, continue
		}
		// Skip hidden/system files
		name := info.Name()
		if strings.HasPrefix(name, ".") || strings.HasPrefix(name, "$") {
			return nil
		}
		// Skip very large files (>500MB)
		if info.Size() > 500*1024*1024 {
			return nil
		}
		// Check budget
		if totalBytes+info.Size() > budget {
			return filepath.SkipAll
		}

		relPath, err := filepath.Rel(srcDir, path)
		if err != nil {
			return nil //nolint:nilerr // best-effort: absent/unreadable source → skip, continue
		}

		dstPath := filepath.Join(dstDir, relPath)
		dstParent := filepath.Dir(dstPath)
		if err := os.MkdirAll(dstParent, 0o755); err != nil {
			return nil //nolint:nilerr // best-effort: absent/unreadable source → skip, continue
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return nil //nolint:nilerr // best-effort: absent/unreadable source → skip, continue
		}
		if err := os.WriteFile(dstPath, data, 0o644); err != nil {
			return nil //nolint:nilerr // best-effort: absent/unreadable source → skip, continue
		}

		totalBytes += info.Size()
		count++
		return nil
	})

	return totalBytes, count
}

// InjectData copies slurped user data from scratch into the installed system's
// user home directory, preserving the folder structure.
func InjectData(target string, result *DataSlurpResult, composeFsNative bool) error {
	if result == nil || !result.Found {
		return nil
	}

	var homeBase string
	if composeFsNative {
		homeBase = filepath.Join(target, "state", "os", "default", "var", "home")
	} else {
		homeBase = filepath.Join(target, "var", "home")
	}

	for _, user := range result.Users {
		// Map to first user's home (UID 1000) — most single-user installs
		userHome := homeBase
		entries, err := os.ReadDir(homeBase)
		if err == nil {
			for _, e := range entries {
				if e.IsDir() && !strings.HasPrefix(e.Name(), ".") {
					userHome = filepath.Join(homeBase, e.Name())
					break
				}
			}
		}

		srcUserDir := filepath.Join(result.ScratchDir, user.Name)
		for _, cat := range user.Categories {
			srcCat := filepath.Join(srcUserDir, cat.Name)
			dstCat := filepath.Join(userHome, cat.Name)

			if err := os.MkdirAll(dstCat, 0o755); err != nil {
				continue
			}

			// Use cp -a for efficient recursive copy with metadata
			if err := runner.Run("cp", "-a", srcCat+"/.", dstCat+"/"); err != nil {
				progress.Info(fmt.Sprintf("Warning: failed to inject %s/%s: %v", user.Name, cat.Name, err))
				continue
			}
		}

		// Set ownership
		_ = runner.Run("chown", "-R", "1000:1000", userHome)
	}

	_ = runner.Run("restorecon", "-R", homeBase)
	progress.Info(fmt.Sprintf("Injected %s of user data into installed system", humanBytes(result.TotalBytes)))
	return nil
}

// categoryPath maps a category name to its Windows profile-relative path.
func categoryPath(name string) string {
	for _, cat := range userDataCategories {
		if strings.EqualFold(cat.Name, name) {
			return cat.Path
		}
	}
	return ""
}
